In [2]:
import pandas as pd

In [11]:
df=pd.read_csv("../00_data/sba_clean_full.csv")
df.head()

,LoanNr_ChkDgt,Name,City,State,Zip,Bank,BankState,NAICS,ApprovalDate,ApprovalFY,...,BalanceGross_num,NAICS_sector,IsFranchise,NewExist_f,UrbanRural_f,PaidInFull,SBA_Portion,RevLineCr_f,LowDoc_f,GFC_Period
0,1000146010,CARVEL,APEX,NC,27502,STEARNS BK NATL ASSOC,MN,445299,7-Feb-06,2006,...,0,44,Yes,New,Urban,1,0.75,No,No,Pre-GFC
1,1000446006,SUBWAY,LITTLE ROCK,AR,72223,HOPE FCU,MS,722211,7-Feb-06,2006,...,0,72,No,Existing,Urban,1,0.85,No,No,Pre-GFC
2,1000506000,WEYLAND CORPORATION,CAMARILLO,CA,93010,WELLS FARGO BANK NATL ASSOC,SD,611110,7-Feb-06,2006,...,0,61,No,New,Urban,1,0.50,Yes,No,Pre-GFC
3,1000516003,CHICAGO BRICK UNLIMITED INC,MIAMI,FL,33186,"CITIBANK, N.A.",FL,238140,7-Feb-06,2006,...,0,23,No,Existing,Urban,1,0.50,Yes,No,Pre-GFC
4,1000526006,"RZI, INC.",NEW ORLEANS,LA,70130,BUSINESS RES. CAP. SPECIALTY B,LA,532490,7-Feb-06,2006,...,0,53,No,Existing,Urban,1,0.85,No,No,Pre-GFC

In [12]:
df.describe()

,LoanNr_ChkDgt,Zip,NAICS,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,DisbursementGross_num,ChgOffPrinGr_num,PropPaid,GrAppv_num,SBA_Appv_num,BalanceGross_num,NAICS_sector,PaidInFull,SBA_Portion
count,3.302770e+05,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,330277.000000,3.302770e+05,3.302770e+05,330277.000000,3.302770e+05,3.302770e+05,330277.000000,330277.000000,330277.000000,330277.000000
mean,3.802474e+09,50717.312165,508569.900611,2005.391480,81.421349,7.969456,1.266125,1.955710,5.455957,1439.479449,1.180349,1.511612e+05,1.612265e+04,0.822825,1.279352e+05,9.311614e+04,6.097854,50.513981,0.719932,0.594916
std,2.243393e+09,31826.613265,169003.760984,2.516627,57.375510,31.905246,0.441931,14.735029,15.710685,9382.885885,0.384478,2.539080e+05,6.398491e+04,0.313647,2.385368e+05,1.960863e+05,2261.343606,17.043431,0.449033,0.159546
min,1.000146e+09,0.000000,111110.000000,1994.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,4.000000e+03,0.000000e+00,-6.367300,1.000000e+03,5.000000e+02,0.000000,11.000000,0.000000,0.050000
25%,2.039015e+09,19946.000000,423910.000000,2004.000000,49.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,2.648500e+04,0.000000e+00,0.703092,2.500000e+04,1.250000e+04,0.000000,42.000000,0.000000,0.500000
50%,3.049704e+09,48864.000000,513322.000000,2006.000000,84.000000,3.000000,1.000000,0.000000,2.000000,1.000000,1.000000,6.000000e+04,0.000000e+00,1.000000,5.000000e+04,2.500000e+04,0.000000,51.000000,1.000000,0.500000
75%,5.494624e+09,83263.000000,621210.000000,2007.000000,84.000000,8.000000,2.000000,2.000000,6.000000,1.000000,1.000000,1.500000e+05,9.387000e+03,1.000000,1.000000e+05,6.375000e+04,0.000000,62.000000,1.000000,0.750000
max,9.984863e+09,99999.000000,928120.000000,2010.000000,527.000000,8000.000000,2.000000,5085.000000,4441.000000,92000.000000,2.000000,1.144632e+07,1.999999e+06,1.000000,4.000000e+06,4.000000e+06,996262.000000,92.000000,1.000000,1.000000

In [13]:
len(df.columns)

42