In [21]:
import pandas as pd

These are the predictors we selected through eda process

In [22]:
subset_list=['ApprovalFY',
 'DisbursementGross_num',
 'State',
 'UrbanRural_f',
 'SBA_Portion',
 'NAICS_sector',
 'NoEmp',
 'SBA_Appv_num', 'GFC_Period','Bank','PaidInFull']

In [23]:
train_df=pd.read_csv("../00_data/split_data/train.csv")

In [24]:
train_df=train_df[subset_list]
train_df

,ApprovalFY,DisbursementGross_num,State,UrbanRural_f,SBA_Portion,NAICS_sector,NoEmp,SBA_Appv_num,GFC_Period,Bank,PaidInFull
0,2005,50000.0,NY,Urban,0.50,42,2,25000.0,Pre-GFC,FIRST NIAGARA BANK NATL ASSOC,1
1,2007,65000.0,NY,Urban,0.50,54,1,20000.0,Pre-GFC,"CITIBANK, N.A.",1
2,2007,56245.0,MA,Urban,0.50,33,4,12500.0,Pre-GFC,CITIZENS BANK NATL ASSOC,0
3,2006,35006.0,VA,Urban,0.50,45,2,7500.0,Pre-GFC,BANK OF AMERICA NATL ASSOC,0
4,2005,20000.0,IL,Urban,0.50,56,15,10000.0,Pre-GFC,CAPITAL ONE NATL ASSOC,0
...,...,...,...,...,...,...,...,...,...,...,...
165132,2006,16600.0,VT,Rural,0.50,23,1,5000.0,Pre-GFC,CITIZENS BANK NATL ASSOC,1
165133,2008,5000.0,LA,Urban,0.85,71,2,4250.0,GFC,"SUPERIOR FINANCIAL GROUP, LLC",0
165134,2002,25000.0,NY,Urban,0.50,54,1,12500.0,Pre-GFC,BANK OF AMERICA NATL ASSOC,1
165135,2005,119960.0,MA,Rural,0.50,56,4,15000.0,Pre-GFC,BERKSHIRE BANK,1
165136,2008,128500.0,VA,Urban,0.85,53,2,109225.0,GFC,"PNC BANK, NATIONAL ASSOCIATION",0

In [25]:
train_df_subset=train_df.sample(n=50000, random_state=42)
train_df_subset

,ApprovalFY,DisbursementGross_num,State,UrbanRural_f,SBA_Portion,NAICS_sector,NoEmp,SBA_Appv_num,GFC_Period,Bank,PaidInFull
14004,2008,510672.0,FL,Rural,0.500000,42,35,150000.0,GFC,REGIONS BANK,1
78435,2007,87569.0,OH,Urban,0.500000,62,1,25000.0,Pre-GFC,THE HUNTINGTON NATIONAL BANK,1
107176,2005,30000.0,MD,Urban,0.500000,56,2,7500.0,Pre-GFC,BANK OF AMERICA NATL ASSOC,1
11832,2005,10050.0,PA,Rural,0.500000,45,2,5000.0,Pre-GFC,FIRST COMMONWEALTH BANK,1
35043,2008,6000.0,OH,Urban,0.500000,53,0,3000.0,GFC,THE HUNTINGTON NATIONAL BANK,1
...,...,...,...,...,...,...,...,...,...,...,...
146638,2008,25000.0,NY,Urban,0.500000,44,1,12500.0,GFC,JPMORGAN CHASE BANK NATL ASSOC,1
26174,2009,100000.0,MA,Urban,0.500000,44,17,50000.0,GFC,SANTANDER BANK NATL ASSOC,1
54258,2004,168300.0,MO,Rural,0.750000,53,7,135000.0,Pre-GFC,MID-MISSOURI BANK,0
127591,1999,172949.0,GA,Urban,0.750001,44,7,129712.0,Pre-GFC,SUNMARK COMMUNITY BANK,1
126579,2006,5000.0,CA,Urban,0.500000,54,4,2500.0,Pre-GFC,BANK OF AMERICA NATL ASSOC,1

In [26]:
train_df_subset.to_csv("../00_data/cleaned_smaller_subsets/train_50k_subset.csv", index=False)